### ISSUE TITLE
Any plan for supporting the latest ROS version?

### ISSUE THREAD

**Issue by JaehyunShim** [alsora/ros2-ORB_SLAM2#1]
Hi, 

As the title says, ROS2 Foxy has been released and I wonder if you have any plan to make this package support the latest version.
Since Bouncy was not one of those LTS versions and also it hit EOL already, I believe they would not be many users who will use this package in its current form.
Dashing also already hit EO and Eloquent is only a 1-year LTS version so Foxy should be the best option. 

Ryan

**Comment by alsora** [comment]
Hi, it should be quite simple to port this to Foxy, will look into it in the next days.

**Comment by JaehyunShim** [comment]
Thanks a lot!

Ryan

**Comment by alsora** [comment]
I just updated the package and the provided Dockerfile to ROS 2 Foxy

**Comment by JaehyunShim** [comment]
@alsora 

Thank you very much. I will test it and get back to you soon.

Ryan
