### ISSUE TITLE
Segmentation fault while running orbslam3 on ros2 gazebo 

### ISSUE THREAD

**Issue by raviS123-dot** [alsora/ros2-ORB_SLAM2#19]
v3@v3:~/ORB_SLAM3$ ros2 run orbslam3 mono /home/v3/colcon_ws/src/orbslam3_ros2/vocabulary/ORBvoc.txt /home/v3/colcon_ws/src/orbslam3_ros2/config/rgb-d/TUM1.yaml 

ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Initialization of Atlas from scratch 
Creation of new map with id: 0
Creation of new map with last KF id: 0
Seq. Name: 

Camera Parameters: 
- Camera: Pinhole
- Image scale: 1
- fx: 517.306
- fy: 516.469
- cx: 318.643
- cy: 255.314
- k1: 0.262383
- k2: -0.953104
- p1: -0.005358
- p2: 0.002628
- k3: 1.16331
- fps: 30
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7
There are 1 cameras in the atlas
Camera 0 is pinhole
Starting the Viewer
[ros2run]: Segmentation fault

**Comment by alsora** [comment]
This is a repository for a ROS 2 wrapper of orbslam2 (which is not even maintained anymore) you should open the issue elsewhere.
