### ISSUE TITLE
Not receiving any frames

### ISSUE THREAD

**Issue by nedo99** [alsora/ros2-ORB_SLAM2#2]
Hi,

I recently built the ros package. Running on Ubuntu 20.04 with ROS foxy. I run
`ros2 run ros2_orbslam mono ../ORB_SLAM2/Vocabulary/ORBvoc.txt ../ros2-ORB_SLAM2/src/rgbd/TUM1.yaml`

I get two displays and text saying "Waiting for images". I see that mono example waits for data on `/camera` topic and I have realsense camera connected with topics:
```
/camera/color/camera_info
/camera/color/image_raw
/camera/depth/camera_info
/camera/depth/color/points
/camera/depth/image_rect_raw
/camera/extrinsics/depth_to_color
/parameter_events
/rosout
/tf
/tf_static
```
but still nothing. I tried replaying the bag file and redirecting `/camera/color/image_raw` to `/camera`, but nothing changes.

On which topic should I forward the image data?

I get this warning https://github.com/stevenlovegrove/Pangolin/issues/644, but I still get two windows open.

Regards,
Nedim

**Comment by nedo99** [comment]
One update. When I run without ROS, just monocular examples taking the dataset from README here https://github.com/raulmur/ORB_SLAM2 works fine.

**Comment by nedo99** [comment]
Found the issue. Intel RealSense camera requires `RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT` for `rmw_qos_reliability_policy_t`. After it is set, images are being received.

Regards,
Nedim

**Comment by alsora** [comment]
Hi!
Sorry for not looking into this, I'm glad you find the solution.
